/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseRouteImport } from './routes/use'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as ChangelogSlugRouteImport } from './routes/changelog.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as PublicLegalRouteImport } from './routes/_public.legal'
import { Route as PublicHelpRouteImport } from './routes/_public.help'
import { Route as PublicHelpIndexRouteImport } from './routes/_public.help.index'
import { Route as PublicHelpSlugRouteImport } from './routes/_public.help.$slug'
import { Route as AuthSignUpSplatRouteImport } from './routes/_auth.sign-up.$'
import { Route as AuthSignInSplatRouteImport } from './routes/_auth.sign-in.$'
import { Route as PublicHelpGuidesSlugRouteImport } from './routes/_public.help.guides.$slug'

const UseRoute = UseRouteImport.update({
  id: '/use',
  path: '/use',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any).lazy(() => import('./routes/_public.index.lazy').then((d) => d.Route))
const ChangelogSlugRoute = ChangelogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ChangelogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const PublicLegalRoute = PublicLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => PublicRoute,
} as any).lazy(() => import('./routes/_public.legal.lazy').then((d) => d.Route))
const PublicHelpRoute = PublicHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHelpIndexRoute = PublicHelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicHelpRoute,
} as any)
const PublicHelpSlugRoute = PublicHelpSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicHelpRoute,
} as any).lazy(() =>
  import('./routes/_public.help.$slug.lazy').then((d) => d.Route),
)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => AuthRoute,
} as any)
const PublicHelpGuidesSlugRoute = PublicHelpGuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => PublicHelpRoute,
} as any).lazy(() =>
  import('./routes/_public.help.guides.$slug.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/use': typeof UseRoute
  '/help': typeof PublicHelpRouteWithChildren
  '/legal': typeof PublicLegalRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/help/$slug': typeof PublicHelpSlugRoute
  '/help/': typeof PublicHelpIndexRoute
  '/help/guides/$slug': typeof PublicHelpGuidesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/use': typeof UseRoute
  '/legal': typeof PublicLegalRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/help/$slug': typeof PublicHelpSlugRoute
  '/help': typeof PublicHelpIndexRoute
  '/help/guides/$slug': typeof PublicHelpGuidesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/use': typeof UseRoute
  '/_public/help': typeof PublicHelpRouteWithChildren
  '/_public/legal': typeof PublicLegalRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/sign-in/$': typeof AuthSignInSplatRoute
  '/_auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/_public/help/$slug': typeof PublicHelpSlugRoute
  '/_public/help/': typeof PublicHelpIndexRoute
  '/_public/help/guides/$slug': typeof PublicHelpGuidesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/changelog'
    | '/robots.txt'
    | '/use'
    | '/help'
    | '/legal'
    | '/blog/$slug'
    | '/changelog/$slug'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/help/$slug'
    | '/help/'
    | '/help/guides/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/changelog'
    | '/robots.txt'
    | '/use'
    | '/legal'
    | '/blog/$slug'
    | '/changelog/$slug'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/help/$slug'
    | '/help'
    | '/help/guides/$slug'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/blog'
    | '/changelog'
    | '/robots.txt'
    | '/use'
    | '/_public/help'
    | '/_public/legal'
    | '/blog/$slug'
    | '/changelog/$slug'
    | '/_public/'
    | '/_auth/sign-in/$'
    | '/_auth/sign-up/$'
    | '/_public/help/$slug'
    | '/_public/help/'
    | '/_public/help/guides/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ChangelogRoute: typeof ChangelogRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  UseRoute: typeof UseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use': {
      id: '/use'
      path: '/use'
      fullPath: '/use'
      preLoaderRoute: typeof UseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/changelog/$slug': {
      id: '/changelog/$slug'
      path: '/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ChangelogSlugRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_public/legal': {
      id: '/_public/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof PublicLegalRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/help': {
      id: '/_public/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof PublicHelpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/help/': {
      id: '/_public/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof PublicHelpIndexRouteImport
      parentRoute: typeof PublicHelpRoute
    }
    '/_public/help/$slug': {
      id: '/_public/help/$slug'
      path: '/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof PublicHelpSlugRouteImport
      parentRoute: typeof PublicHelpRoute
    }
    '/_auth/sign-up/$': {
      id: '/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in/$': {
      id: '/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/help/guides/$slug': {
      id: '/_public/help/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/help/guides/$slug'
      preLoaderRoute: typeof PublicHelpGuidesSlugRouteImport
      parentRoute: typeof PublicHelpRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInSplatRoute: AuthSignInSplatRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicHelpRouteChildren {
  PublicHelpSlugRoute: typeof PublicHelpSlugRoute
  PublicHelpIndexRoute: typeof PublicHelpIndexRoute
  PublicHelpGuidesSlugRoute: typeof PublicHelpGuidesSlugRoute
}

const PublicHelpRouteChildren: PublicHelpRouteChildren = {
  PublicHelpSlugRoute: PublicHelpSlugRoute,
  PublicHelpIndexRoute: PublicHelpIndexRoute,
  PublicHelpGuidesSlugRoute: PublicHelpGuidesSlugRoute,
}

const PublicHelpRouteWithChildren = PublicHelpRoute._addFileChildren(
  PublicHelpRouteChildren,
)

interface PublicRouteChildren {
  PublicHelpRoute: typeof PublicHelpRouteWithChildren
  PublicLegalRoute: typeof PublicLegalRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicHelpRoute: PublicHelpRouteWithChildren,
  PublicLegalRoute: PublicLegalRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ChangelogRouteChildren {
  ChangelogSlugRoute: typeof ChangelogSlugRoute
}

const ChangelogRouteChildren: ChangelogRouteChildren = {
  ChangelogSlugRoute: ChangelogSlugRoute,
}

const ChangelogRouteWithChildren = ChangelogRoute._addFileChildren(
  ChangelogRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ChangelogRoute: ChangelogRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  UseRoute: UseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
